@qa_release
Feature: company CRUD
  Scenario: update - success
    # When User submit term with method POST as sazande in rest
    When User submit "update" "company"-"<id>" as <user> in rest
      | id*int | person.id*int | person.nationalCode  | person.landlineNumber  | person.addresses.0.id*int | person.addresses.0.reference | person.addresses.0.postalCode | person.addresses.0.city.id*int | person.addresses.0.city.name | person.addresses.0.city.province.id*int | person.addresses.0.city.province.name | person.addresses.0.city.province.slug | person.addresses.0.city.slug | person.addresses.0.id*int | person.addresses.0.reference | person.addresses.0.postalCode | person.addresses.0.city.id*int | person.addresses.0.city.name | person.addresses.0.city.province.id*int | person.addresses.0.city.province.name | person.addresses.0.city.province.slug | person.addresses.0.city.slug | fullName   | domain   | registerationNumber   | economicCode   | engineeringLicenseNumber   | registerationDate   |
      | <id>   | <personId>    | <personNationalCode> | <personLandlineNumber> | <personAddressesid>       | <personAddressesreference>   | <personAddressespostalCode>   | <personAddressescityId>        | <personAddressescityName>    | <personAddressescityProvinceId>         | <personAddressescityProvinceName>     | <personAddressescityProvinceSlug>     | <personAddressescitySlug>    | <personAddressesid>       | <personAddressesreference>   | <personAddressespostalCode>   | <personAddressescityId>        | <personAddressescityName>    | <personAddressescityProvinceId>         | <personAddressescityProvinceName>     | <personAddressescityProvinceSlug>     | <personAddressescitySlug>    | <fullName> | <domain> | <registerationNumber> | <economicCode> | <engineeringLicenseNumber> | <registerationDate> |
    # Then User wait for '900' secound

    Then Check response data and statusCode <statusCode>
      | id*int | person.id*int | person.nationalCode  | person.landlineNumber  | person.addresses.0.reference | person.addresses.0.postalCode | person.addresses.0.city.id*int | person.addresses.0.city.name | person.addresses.0.city.province.id*int | person.addresses.0.city.province.name | person.addresses.0.city.province.slug | person.addresses.0.city.slug | person.addresses.0.id*int | person.addresses.0.reference | person.addresses.0.postalCode | person.addresses.0.city.id*int | person.addresses.0.city.name | person.addresses.0.city.province.id*int | person.addresses.0.city.province.name | person.addresses.0.city.province.slug | person.addresses.0.city.slug | fullName   | domain   | registerationNumber   | economicCode   | engineeringLicenseNumber   | registerationDate   |
      | <id>   | <personId>    | <personNationalCode> | <personLandlineNumber> | <personAddressesreference>   | <personAddressespostalCode>   | <personAddressescityId>        | <personAddressescityName>    | <personAddressescityProvinceId>         | <personAddressescityProvinceName>     | <personAddressescityProvinceSlug>     | <personAddressescitySlug>    | <personAddressesid>       | <personAddressesreference>   | <personAddressespostalCode>   | <personAddressescityId>        | <personAddressescityName>    | <personAddressescityProvinceId>         | <personAddressescityProvinceName>     | <personAddressescityProvinceSlug>     | <personAddressescitySlug>    | <fullName> | <domain> | <registerationNumber> | <economicCode> | <engineeringLicenseNumber> | <registerationDate> |

    Examples:
      | user       | id | personId | personNationalCode | personLandlineNumber | personAddressesid | personAddressesreference                     | personAddressespostalCode | personAddressescityId | personAddressescityName | personAddressescityProvinceId | personAddressescityProvinceName | personAddressescityProvinceSlug | personAddressescitySlug | personAddressesid | personAddressesreference                     | personAddressespostalCode | personAddressescityId | personAddressescityName | personAddressescityProvinceId | personAddressescityProvinceName | personAddressescityProvinceSlug | personAddressescitySlug | fullName | domain       | registerationNumber | economicCode | engineeringLicenseNumber | registerationDate        | statusCode |
      | "admin"    | 1  | 1        | 0370717194         | 03538342317          | 1                 | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | 1                 | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | (هیواتک) | hyvatech.com | 3298323             | 323298       | 3298323                  | 2023-05-10T14:24:42.918Z | 200        |
      | "sazande"  | 2  | 3        | 0399717194         | 03538342317          |                   | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | 1                 | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | (هیواتک) | hyvatech.com | 3298323             | 323298       | 3298323                  | 2023-05-10T14:24:42.918Z | 200        |
      | "sazande"  | 1  | 1        | 0399717194         | 03538342317          |                   | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | 1                 | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | (هیواتک) | hyvatech.com | 3298323             | 323298       | 3298323                  | 2023-05-10T14:24:42.918Z | 403        |
      | "customer" | 2  | 3        | 0399717194         | 03538342317          |                   | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | 1                 | (یزد شهرک شکوهیه بلوار نصیر کوچه ۲۱ پلاک ۱۰) | 982398323                 | 1111                  | (یزد)                   | 31                            | (یزد)                           | (یزد)                           | (یزد)                   | (هیواتک) | hyvatech.com | 3298323             | 323298       | 3298323                  | 2023-05-10T14:24:42.918Z | 403        |








